- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
Fixes #115, though quite dubious on this one, lookng forward to seeing what's said
> Ensure a single event when changing address

- core/class-extension-core.php
- core/class-plugin-installer.php
- includes/wsal-functions.php
- wp-security-audit-log/custom-alerts.php
- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
> Add event s for webhooks

- includes/wsal-functions.php
- wp-security-audit-log/custom-alerts.php
- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php
> Adding SKU to product events

- wp-security-audit-log/custom-alerts.php
- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
> adding 9122

- wp-security-audit-log/custom-alerts.php
- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
> Adding details to 9041

- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
> Update WC function

- wp-security-audit-log/custom-alerts.php
- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php
> Tweaks & Fixes

- readme.txt
- wp-security-audit-log/custom-alerts.php
- wsal-woocommerce.php
Fixes https://github.com/wpwhitesecurity/wsal-woocommerce/issues/162.
> Change 9135 event description and bump version number.

- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
Fixes https://github.com/wpwhitesecurity/wsal-woocommerce/issues/170.
> Improve object type checking in various places.

- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
> Correcting sale price string

- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
> Update how we lookup old webhook data

- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
Fixes https://github.com/wpwhitesecurity/wsal-woocommerce/issues/174
> Ensure events fire once

- includes/wsal-functions.php
- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php
> Update access of was_triggered function

- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
> Fix typo at line 2115 in main sensor

- includes/wsal-functions.php
> Simply logic when saving setting

- includes/wsal-functions.php
Fixes error seen here https://github.com/wpwhitesecurity/wp-security-audit-log-premium/issues/2691 though we still need to determine why this is happening now
Iv confirmed its NOT an issue running current WC extension release + WSAL 4.4.1.1
> Fix potential error in activity log

- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
> Ensure old data is present

- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
> Pruning unused function and move to WSAL class function

- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
> Sites with WC disabled showing error in log Potential fix

- wp-security-audit-log/custom-alerts.php
- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
> Ensure secret changes are tracked

- wp-security-audit-log/custom-alerts.php
- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
> Adding 9140 > 9143

- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
> Ensure fee change is reported

- wp-security-audit-log/custom-alerts.php
- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
> Adding event 9154 - detect order opened in editor

- wp-security-audit-log/custom-alerts.php
> Correcting event ID

- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php
> Ensure 1st edits give event

- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php
> Ensure occurence is always avaialable

- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php
> Ensure occurence is always avaialable (#244)

- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php
> Adding check for boolean getter

- wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php
> Allow 9073 event to fire
